name: CI
on: [push]
jobs:
  run:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        version: 16.x

    - name: Install
      run: yarn install

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test
