name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - uses: pnpm/action-setup@v2.2.4

    - name: Install Dependencies
      run: pnpm install

    - name: Lint
      run: pnpm lint

    - name: Test
      run: pnpm test
